# Generated by Django 6.1.1 on 2026-10-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва кафедри')),
                ('head_name', models.CharField(max_length=255, verbose_name='Завідувач кафедри')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Факультет охорони здоров'я НаУКМА", max_length=255)),
                ('description', models.TextField(verbose_name='Опис факультету')),
                ('contacts', models.TextField(verbose_name='Контактна інформація')),
            ],
            options={
                'verbose_name': 'Інформація про факультет',
                'verbose_name_plural': 'Інформація про факультет',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=50, verbose_name='Код спеціальності')),
                ('description', models.TextField(verbose_name='Опис')),
                ('coordinator_name', models.CharField(max_length=255, verbose_name="Ім'я координатора")),
                ('coordinator_contact', models.CharField(max_length=255, verbose_name='Контакт координатора')),
                ('disciplines', models.TextField(help_text='Перелік дисциплін (через кому або з нового рядка)', verbose_name='Список дисциплін')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='foz_website.department', verbose_name='Випускова кафедра')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я викладача")),
                ('position', models.CharField(max_length=255, verbose_name='Посада')),
                ('degree', models.CharField(max_length=255, verbose_name='Науковий ступінь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='foz_website.department', verbose_name='Кафедра')),
            ],
        ),
    ]
