# Generated by Django 6.1.1 on 2026-10-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foz_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.TextField(default='', null=True, blank=True, verbose_name='Університет')),
                ('languages', models.TextField(verbose_name='Мови навчання')),
                ('places', models.TextField(verbose_name='Кількість місць')),
                ('deadline', models.DateField(verbose_name='Дедлайн подачі')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
        ),
    ]