# Generated by Django 6.1.1 on 2026-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foz_website', '0003_seed_exchange_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='university',
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='university_name',
            field=models.CharField(default='', max_length=255, verbose_name='Назва університету'),
        ),
    ]
