# Generated by Django 6.1.1 on 2026-10-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foz_website', '0005_split_university_country_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeprogram',
            name='places',
            field=models.IntegerField(default=1, verbose_name='Кількість місць'),
        ),
    ]
